--[[
    artisan.lua — Laravel-style CLI for the Love2D boilerplate.

    Run from the project root:

        lua artisan.lua list
        lua artisan.lua make:scene InventoryScene
        lua artisan.lua make:entity Bullet
        lua artisan.lua make:service ScoreManager
        lua artisan.lua make:test test_input
        lua artisan.lua make:ui HealthBar
        lua artisan.lua make:config gameplay

    No LÖVE required — pure Lua so it works in CI, scripts, and editors.
]]

local commands = {}
local args = { ... }

-- ---------------------------------------------------------------------------
-- Utilities
-- ---------------------------------------------------------------------------
local function writeFile(path, content)
    local file, err = io.open(path, "w")
    if not file then
        print(("  [error] could not open %s: %s"):format(path, err))
        return false
    end
    file:write(content)
    file:close()
    print(("  [created] %s"):format(path))
    return true
end

local function fileExists(path)
    local f = io.open(path, "r")
    if f then f:close(); return true end
    return false
end

-- ---------------------------------------------------------------------------
-- Template generators
-- ---------------------------------------------------------------------------
local function sceneTemplate(name)
    return ([[
-- %s — scene stub
-- Generated by artisan make:scene. Edit me.
local Scene = require("core.Scene")

local %s = Scene:extend("%s")

function %s:enter()
    -- called once when this scene becomes active
end

function %s:exit()
    -- called once when leaving this scene
end

function %s:update(dt)
    -- game logic, called every frame
end

function %s:draw()
    -- rendering, called every frame
end

function %s:keypressed(key, scancode, isrepeat) end
function %s:mousepressed(x, y, button) end

return %s
]]):format(name, name, name, name, name, name, name, name, name, name)
end

local function entityTemplate(name)
    return ([[
-- %s — entity stub
-- Generated by artisan make:entity. Edit me.
local Entity = require("Entities.Entity")

local %s = Entity:extend("%s")

function %s:new(x, y, opts)
    %s.super.new(self, x, y, opts)
    -- custom fields here
    return self
end

function %s:update(dt)
    %s.super.update(self, dt)
    -- custom logic here
end

function %s:draw()
    %s.super.draw(self)
    -- custom rendering here
end

return %s
]]):format(name, name, name, name, name, name, name, name, name, name, name)
end

local function serviceTemplate(name)
    return ([[
-- %s - service stub
-- Generated by artisan make:service. Edit me.
local ServiceProvider = require("core.ServiceProvider")

local %s = ServiceProvider:extend("%s")

function %s:register()
    -- Bind things in app:bind("name", value)
    -- e.g. self:bind("score", { value = 0 })
end

function %s:boot()
    -- Called after all providers are registered.
    -- Safe to resolve other services here.
end

return %s
]]):format(name, name, name, name, name, name)
end

local function testTemplate(name)
    return ([[
-- %s — test stub
-- Generated by artisan make:test. Edit me.
local Test = require("tests.TestCase")

local %s = Test:extend("%s")

function %s:test_truth()
    self:assertTrue(true)
end

function %s:test_equality()
    self:assertEquals(2 + 2, 4)
end

return %s
]]):format(name, name, name, name, name, name)
end

local function uiTemplate(name)
    return ([[
-- %s - UI component stub
-- Generated by artisan make:ui. Edit me.
local Class = require("core.Class")

local %s = Class:extend("%s")

function %s:new(opts)
    opts = opts or {}
    self.x = opts.x or 0
    self.y = opts.y or 0
    self.w = opts.w or 100
    self.h = opts.h or 30
    return self
end

function %s:update(dt) end
function %s:draw()    end

return %s
]]):format(name, name, name, name, name, name, name)
end

local function configTemplate(name)
    return ([[
-- config/%s.lua — configuration stub
return {
    -- Add your config keys here.
}
]]):format(name)
end

-- ---------------------------------------------------------------------------
-- Command registry
-- ---------------------------------------------------------------------------
commands.list = function()
    print("Available commands:")
    for name, _ in pairs(commands) do
        if name ~= "list" then
            print("  make:" .. name)
        end
    end
end

commands.scene = function(name)
    if not name then return print("Usage: artisan make:scene <Name>") end
    local path = "scenes/" .. name .. ".lua"
    if fileExists(path) then return print("  [skip] " .. path .. " already exists") end
    writeFile(path, sceneTemplate(name))
end

commands.entity = function(name)
    if not name then return print("Usage: artisan make:entity <Name>") end
    local path = "app/Entities/" .. name .. ".lua"
    if fileExists(path) then return print("  [skip] " .. path .. " already exists") end
    writeFile(path, entityTemplate(name))
end

commands.service = function(name)
    if not name then return print("Usage: artisan make:service <Name>") end
    local path = "app/Services/" .. name .. ".lua"
    if fileExists(path) then return print("  [skip] " .. path .. " already exists") end
    writeFile(path, serviceTemplate(name))
end

commands.test = function(name)
    if not name then return print("Usage: artisan make:test <name>") end
    local path = "tests/" .. name .. ".lua"
    if fileExists(path) then return print("  [skip] " .. path .. " already exists") end
    writeFile(path, testTemplate(name))
end

commands.ui = function(name)
    if not name then return print("Usage: artisan make:ui <Name>") end
    local path = "app/UI/" .. name .. ".lua"
    if fileExists(path) then return print("  [skip] " .. path .. " already exists") end
    writeFile(path, uiTemplate(name))
end

commands.config = function(name)
    if not name then return print("Usage: artisan make:config <name>") end
    local path = "config/" .. name .. ".lua"
    if fileExists(path) then return print("  [skip] " .. path .. " already exists") end
    writeFile(path, configTemplate(name))
end

-- ---------------------------------------------------------------------------
-- Dispatcher
-- ---------------------------------------------------------------------------
local cmd = args[1]
local arg1 = args[2]

if not cmd or cmd == "list" or cmd == "help" then
    commands.list()
    print("")
    print("Run from project root, e.g.:")
    print("  lua artisan.lua make:scene InventoryScene")
    os.exit(0)
end

local makeType = cmd:match("^make:(.+)$")
if not makeType then
    print("Unknown command: " .. tostring(cmd))
    print("Run 'lua artisan.lua list' to see available commands.")
    os.exit(1)
end

local handler = commands[makeType]
if not handler then
    print("Unknown make type: " .. makeType)
    os.exit(1)
end

handler(arg1)
